### ISSUE TITLE
Make snake move faster after each point

### ISSUE THREAD

**Issue by indremak** [indremak/Snake-Game#2]
Every time player gets a point, make snake move faster. 

You can add `speed` property to `gameState` object, use it to control game speed, increase it when player gets a point.

**Comment by jianajavier** [comment]
@indremak I can take this on, can you assign it to me, please?

**Comment by indremak** [comment]
Sure, go ahead!

**Comment by jianajavier** [comment]
@indremak Here's the PR: https://github.com/indremak/Snake-Game/pull/6
