### ISSUE TITLE
Style buttons

### ISSUE THREAD

**Issue by indremak** [indremak/Snake-Game#26]
Now the buttons are default style, style them to look better

**Comment by kushaangowda** [comment]
Can you please assign this to me?

**Comment by indremak** [comment]
@kushaangowda sure 🙂

**Comment by kushaangowda** [comment]
Is it ok if i use bootstrap, or am I supposed to type the code directly into the css file?

**Comment by indremak** [comment]
@kushaangowda I would prefer if you use css.

**Comment by kushaangowda** [comment]
![Screenshot (65)](https://user-images.githubusercontent.com/53338864/95971297-a5ed2a00-0e2e-11eb-963d-9bca5d99c41a.png)
buttons in hover, disabled and enabled states respectively
Is this fine?

**Comment by kushaangowda** [comment]
I have added a new PR
