### ISSUE TITLE
Make game more responsive

### ISSUE THREAD

**Issue by indremak** [indremak/Snake-Game#30]
Game would look better, if game board would be bigger on large screens.

**Comment by amohapatra123** [comment]
can i work on this issue

**Comment by MDShields7** [comment]
Do you mean the number of squares would increase dependent on the user screen? Or the existing squares would scale bigger?

**Comment by indremak** [comment]
The amount of squares should not change but they should scale depending on the screen.

**Comment by albertodeago** [comment]
I'm working on this, will do a PR
