### ISSUE TITLE
Bug: when two buttons are clicked quickly, game is over

### ISSUE THREAD

**Issue by indremak** [indremak/Snake-Game#5]
Steps to reproduce:
1. Snake is moving to the right.
2. Up button is clicked and left button is clicked quickly after that.

Expected results: game shouldn't be over. Snake should move up. 

Actual result: Game is over.

**Comment by pupupulp** [comment]
Hi @indremak ,

I've created a pull request #11 for a simple fix, hoping this helps to close this issue :D :D :D
