### ISSUE TITLE
Add a head to a snake

### ISSUE THREAD

**Issue by indremak** [indremak/Snake-Game#8]
Make first cell of the snake different - to look like a head. You can style it like you want. You can also change style of the whole snake if you want.

**Comment by redice44** [comment]
I'll put something together :)

**Comment by madmaxWMFU** [comment]
Hi @indremak , I would love to help you. Can I?  Please assign me this.

**Comment by evandroLutz** [comment]
Hi, please check my pull request and mark it as 'hacktoberfest-accepted', thank you.

i hope you enjoy the enhancements;
#18
